### ISSUE TITLE
Api antigag

### ISSUE THREAD

**Issue by BrunoSan123** [Podemoscorp/crud#20]
*Seria bom deletar a API, antiga já que foi feito por vcs um MVC.

**Comment by JN513** [comment]
Então, você, fala o outro repositorio ??? Vou ver se apago ele, esse app "API" nesse repositório aqui, e outra coisa.

**Comment by BrunoSan123** [comment]
A tá, mas não é um MVC que vcs criaram aqui?

**Comment by JN513** [comment]
e foi

**Comment by JN513** [comment]
e que a futuramente, queremos expandir um pouco, ai o app ta ai já, kk

**Comment by BrunoSan123** [comment]
ahhh entendi, boa
